name: IPLogin
version: '${version}'
main: com.theonlysd12.iplogin.IPLogin
api-version: 1.19
author: TheOnlySD12
description: Basic PaperMC plugin for IP login
website: https://modrinth.com/plugin/iplogin

commands:
  iplogin:
    description: Access to IPLogin commands
    usage: Type /iplogin <command> <args>