name: IPLogin
version: '${version}'
main: com.theonlysd12.iplogin.IPLogin
api-version: 1.19
author: TheOnlySD12
description: Basic PaperMC plugin for IP login
website: https://github.com/TheOnlySD12/IPLogin

commands:
  setip:
    description: Changes your login IP
    usage: Type /setip <newip> to set your new IP or /setip <player> <newip> to set someone's IP.
    aliases: [ setipaddress ]
  allowalts:
    description: Allows alts
    usage: Type /allowalts <true/false> or /allowalts to find out what the value is set to.